INSERT INTO Modell (modellid, marka, tipus, felszereltseg) VALUES (1, 'Peugeot', '5008', 'Outdoor')
INSERT INTO Modell (modellid, marka, tipus, felszereltseg) VALUES (2, 'Peugeot', '3008', 'Basic')
INSERT INTO Modell (modellid, marka, tipus, felszereltseg) VALUES (3, 'Peugeot', '208', 'Basic')
INSERT INTO Modell (modellid, marka, tipus, felszereltseg) VALUES (4, 'Peugeot', '308', 'Outdoor')
INSERT INTO Modell (modellid, marka, tipus, felszereltseg) VALUES (5, 'Mercedes', 'C63 AMG', '9G-Tronic')
INSERT INTO Modell (modellid, marka, tipus, felszereltseg) VALUES (6, 'Mercedes', 'C63 AMG', 'Alap')
INSERT INTO Modell (modellid, marka, tipus, felszereltseg) VALUES (7, 'BYD', 'Atto 3', 'Comfort')
INSERT INTO Modell (modellid, marka, tipus, felszereltseg) VALUES (8, 'BYD', 'Atto 3', 'Plus')
INSERT INTO Modell (modellid, marka, tipus, felszereltseg) VALUES (9, 'BYD', 'Seal', 'Comfort')
INSERT INTO Modell (modellid, marka, tipus, felszereltseg) VALUES (10, 'BMV', 'X-5', 'Gut')