INSERT INTO Uzletkoto (uzletkotoid, nev, fizetes) VALUES (1, 'Balogh Júlia', 800000)
INSERT INTO Uzletkoto (uzletkotoid, nev, fizetes) VALUES (2, 'Molnár Péter', 750000)
INSERT INTO Uzletkoto (uzletkotoid, nev, fizetes) VALUES (3, 'Juhász Lajos', 820000)
INSERT INTO Uzletkoto (UzletkotoID,Nev,Fizetes) VALUES (4,'Major Zsolt',720000)
INSERT INTO Uzletkoto (UzletkotoID,Nev,Fizetes) VALUES (5,'Szabó Kitti',750000)